forum screen
Kepler-2002/CycleQuest pull request #13
Opened 2024-10-27 08:01 UTC by haochenhan1213

1, bug: accompanist not found
2, forum screen

2024-10-27 08:46 UTC, Kepler-2002 commented on app/build.gradle.kts
> +    implementation ("com.google.accompanist:accompanist-permissions:0.31.3-beta")
这个是干啥的呀？

2024-10-27 08:46 UTC, Kepler-2002 commented on app/src/main/java/com/cyclequest/application/ui/screens/ForumScreen.kt
> +    Card(
Component语义，不要和screens放在一起

2024-10-27 08:46 UTC, Kepler-2002 commented on build.gradle.kts
>      id("org.jetbrains.kotlin.android") version "1.8.21" apply false
这里也是一定要改才能编译通过嘛？

2024-10-27 08:53 UTC, Kepler-2002 requested changes

2024-10-27 08:53 UTC, Kepler-2002 commented on settings.gradle.kts
这个先不变试一下，不行换成阿里云的8.2

2024-10-27 08:53 UTC, Kepler-2002 commented on settings.gradle.kts
> +        maven { url = uri("https://maven.aliyun.com/repository/google") }
这些没问题

2024-10-27 09:13 UTC, closed without merging

2024-10-28 14:41 UTC, haochenhan1213 commented on app/build.gradle.kts
> +    implementation ("com.google.accompanist:accompanist-permissions:0.31.3-beta")
原先的master，这个不加的情况下，我也编译不过

2024-10-28 14:48 UTC, Kepler-2002 commented on app/build.gradle.kts
> +    implementation ("com.google.accompanist:accompanist-permissions:0.31.3-beta")
ok问题不大，把gradle版本对齐了之后记得拉一下最新的master代码 合并之后辛苦再提一个pr